# Per-account Health Score report for the Ops team. Lists every account
# with its latest snapshot (total + per-group normalized scores) so Ops can
# spot churn risk and drill into the metric breakdown for each row.
#
# Data is generated by `SuperAdmin::HealthScore::DailySnapshotJob` (runs
# 03:00 UTC). This controller only reads from `account_health_scores`.
class SuperAdmin::Reports::HealthScoreController < SuperAdmin::ApplicationController
  def show; end

  def data
    rows = latest_snapshots_by_account.map { |snapshot| serialize(snapshot) }
    accounts_without_score.each { |account| rows << serialize_missing(account) }
    rows.sort_by! { |row| [row[:score].nil? ? 1 : 0, row[:score] || 0, row[:account_name].to_s.downcase] }

    render json: {
      accounts: rows,
      counts: count_bands(rows),
      computed_at: rows.filter_map { |r| r[:captured_on] }.max
    }
  end

  private

  # One row per account: the most recent `account_health_scores` entry. We
  # eager-load the account so per-row serialization stays N+1-free.
  def latest_snapshots_by_account
    AccountHealthScore
      .where(id: AccountHealthScore.select('DISTINCT ON (account_id) id').order(:account_id, captured_on: :desc))
      .includes(:account)
  end

  def accounts_without_score
    scored_ids = AccountHealthScore.distinct.pluck(:account_id)
    Account.where.not(id: scored_ids)
  end

  def serialize(snapshot)
    breakdown = snapshot.breakdown || {}
    {
      account_id: snapshot.account_id,
      account_name: snapshot.account.name,
      score: snapshot.score,
      band: band_for(snapshot.score),
      captured_on: snapshot.captured_on.iso8601,
      groups: breakdown.fetch('groups', {}),
      metrics: breakdown.fetch('metrics', {}),
      kill_clause: breakdown['kill_clause'],
      phase: breakdown['phase'],
      account_age_days: breakdown['account_age_days']
    }
  end

  # When the daily job hasn't produced a snapshot for an account yet (brand
  # new account, or the job hasn't run since the account was created), still
  # surface it in the report so Ops doesn't think it disappeared.
  def serialize_missing(account)
    {
      account_id: account.id,
      account_name: account.name,
      score: nil,
      band: nil,
      captured_on: nil,
      groups: {},
      metrics: {},
      kill_clause: nil,
      phase: nil,
      account_age_days: nil
    }
  end

  def band_for(score)
    return nil if score.nil?
    return 'red' if score <= 40
    return 'yellow' if score <= 65
    return 'green' if score <= 85

    'green_strong'
  end

  def count_bands(rows)
    rows.each_with_object(red: 0, yellow: 0, green: 0, green_strong: 0, unscored: 0) do |row, acc|
      key = row[:band]&.to_sym || :unscored
      acc[key] += 1
    end
  end
end
